"""QC thresholds and task definitions — ported from network-behavior-qc/globals.py."""

# Stop signal task
STOP_SUCCESS_ACC_LOW_THRESHOLD = 0.25
STOP_SUCCESS_ACC_HIGH_THRESHOLD = 0.75
GO_RT_THRESHOLD_FMRI = 1000
GO_RT_THRESHOLD_FMRI_DUAL_TASK = 1050

# Go/nogo fMRI exclusion thresholds (both conditions must be met)
GONOGO_GO_ACC_THRESHOLD_1 = 0.75
GONOGO_NOGO_ACC_THRESHOLD_1 = 0.2
GONOGO_GO_ACC_THRESHOLD_2 = 0.5
GONOGO_NOGO_ACC_THRESHOLD_2 = 0.5

# N-back fMRI exclusion thresholds (both conditions must be met)
NBACK_1BACK_MATCH_ACC_COMBINED_THRESHOLD_1 = 0.2
NBACK_1BACK_MISMATCH_ACC_COMBINED_THRESHOLD_1 = 0.75
NBACK_1BACK_MATCH_ACC_COMBINED_THRESHOLD_2 = 0.5
NBACK_1BACK_MISMATCH_ACC_COMBINED_THRESHOLD_2 = 0.5
NBACK_2BACK_MATCH_ACC_COMBINED_THRESHOLD_1 = 0.2
NBACK_2BACK_MISMATCH_ACC_COMBINED_THRESHOLD_1 = 0.75
NBACK_2BACK_MATCH_ACC_COMBINED_THRESHOLD_2 = 0.5
NBACK_2BACK_MISMATCH_ACC_COMBINED_THRESHOLD_2 = 0.5

# All other tasks
ACC_THRESHOLD = 0.55
OMISSION_RATE_THRESHOLD = 0.25

# Trimming detection
LAST_N_TEST_TRIALS = 10
SUMMARY_ROWS = 4
