"""Pure rendering functions for exclusion data.

Public API
----------
render_md(entries)           -> str   Markdown grouped by source with DO-NOT-EDIT stamp.
render_bidsignore(entries)   -> str   One .bidsignore glob line per exclude/trim entry.
check_md_drift(committed, rendered) -> (bool, str)   Detect drift between committed and fresh render.
check_bidsignore_drift(committed, rendered) -> (bool, str)   Same for .bidsignore content.

All functions are pure (no I/O).  The CLI writes only when --output is given.
"""
from __future__ import annotations

from collections import defaultdict

# ---------------------------------------------------------------------------
# Stamps
# ---------------------------------------------------------------------------

_MD_STAMP = "<!-- DO NOT EDIT — generated by 'neuro-run exclusions render-md' -->"
_BIDSIGNORE_STAMP = "# DO NOT EDIT — generated by 'neuro-run exclusions render-bidsignore'"

# Actions that produce a .bidsignore line.
_BIDSIGNORE_ACTIONS = {"exclude", "trim"}


# ---------------------------------------------------------------------------
# render_md
# ---------------------------------------------------------------------------

def render_md(entries: list[dict]) -> str:
    """Render a Markdown document grouped by source from the given entries list.

    Parameters
    ----------
    entries:
        List of exclusion entry dicts (as returned by load_compiled_exclusions).

    Returns
    -------
    str
        Full Markdown document.  Deterministic: sorted by source, then by
        (subject, session, task, run) within each source group.
    """
    lines: list[str] = [
        _MD_STAMP,
        "",
        "# Exclusions",
        "",
    ]

    if not entries:
        lines.append("*(no exclusions)*")
        lines.append("")
        return "\n".join(lines) + "\n"

    by_source: dict[str, list[dict]] = defaultdict(list)
    for e in entries:
        by_source[e.get("source", "unknown")].append(e)

    for source in sorted(by_source.keys()):
        lines.append(f"## Source: {source}")
        lines.append("")
        lines.append("| Subject | Session | Task | Run | Action | Reason |")
        lines.append("|---|---|---|---|---|---|")
        group = sorted(
            by_source[source],
            key=lambda e: (
                e.get("subject", ""),
                e.get("session", ""),
                e.get("task", ""),
                e.get("run", ""),
            ),
        )
        for e in group:
            lines.append(
                f"| {e.get('subject', '-')} "
                f"| {e.get('session', '-')} "
                f"| {e.get('task', '-')} "
                f"| {e.get('run', '-')} "
                f"| {e.get('action', '-')} "
                f"| {e.get('reason', '')} |"
            )
        lines.append("")

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# render_bidsignore
# ---------------------------------------------------------------------------

def _entry_to_bidsignore_glob(entry: dict) -> str | None:
    """Convert a single exclusion entry to a .bidsignore glob line.

    Returns None for entries with actions that should NOT produce a glob
    (e.g. force-include).

    Glob form (functional BOLD, matching the real .bidsignore convention):
        sub-{subject}/ses-{session}/func/sub-{subject}_ses-{session}_task-{task}_run-{run}_echo-*_bold.*

    Field values in entries already carry BIDS prefixes (sub-, ses-, run-)
    but task is stored BARE.  The function normalises to the form the real
    .bidsignore uses.
    """
    action = entry.get("action", "")
    if action not in _BIDSIGNORE_ACTIONS:
        return None

    subject = entry.get("subject", "")    # e.g. "sub-s10"
    session = entry.get("session", "")    # e.g. "ses-05"
    task = entry.get("task", "")          # BARE, e.g. "goNogo"
    run = entry.get("run", "run-*")       # e.g. "run-1" or "run-*"

    # Normalise subject/session to have BIDS prefix.
    if not subject.startswith("sub-"):
        subject = f"sub-{subject}"
    if not session.startswith("ses-"):
        session = f"ses-{session}"
    # task is stored bare; prepend task- for the glob.
    if not task.startswith("task-"):
        task_tag = f"task-{task}"
    else:
        task_tag = task
    # run already has prefix (run-1 / run-*).
    if not run.startswith("run-"):
        run = f"run-{run}"

    return (
        f"{subject}/{session}/func/"
        f"{subject}_{session}_{task_tag}_{run}_echo-*_bold.*"
    )


def render_bidsignore(entries: list[dict]) -> str:
    """Render a .bidsignore file from the given entries list.

    Only entries with action in {'exclude', 'trim'} produce glob lines.
    Lines are sorted for determinism.

    Parameters
    ----------
    entries:
        List of exclusion entry dicts.

    Returns
    -------
    str
        Full .bidsignore content (header comment + sorted glob lines).
    """
    lines: list[str] = [_BIDSIGNORE_STAMP, ""]

    globs: list[str] = []
    for e in entries:
        glob = _entry_to_bidsignore_glob(e)
        if glob is not None:
            globs.append(glob)

    globs_sorted = sorted(set(globs))
    lines.extend(globs_sorted)

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Drift detection helpers
# ---------------------------------------------------------------------------

def check_md_drift(committed: str, rendered: str) -> tuple[bool, str]:
    """Compare a committed Markdown artifact against a freshly rendered version.

    Parameters
    ----------
    committed:
        The content currently on disk / in VCS.
    rendered:
        The output of render_md() for the current entries.

    Returns
    -------
    (drifted, details)
        drifted is True when committed != rendered.
        details is a human-readable diff summary (empty string when no drift).
    """
    if committed == rendered:
        return False, ""

    committed_lines = committed.splitlines()
    rendered_lines = rendered.splitlines()

    import difflib
    diff = list(
        difflib.unified_diff(
            rendered_lines,
            committed_lines,
            fromfile="rendered (fresh)",
            tofile="committed (on-disk)",
            lineterm="",
        )
    )
    details = "\n".join(diff[:40])  # cap for readability
    if len(diff) > 40:
        details += f"\n... ({len(diff) - 40} more diff lines)"
    return True, details


def check_bidsignore_drift(committed: str, rendered: str) -> tuple[bool, str]:
    """Compare a committed .bidsignore artifact against a freshly rendered version.

    Parameters
    ----------
    committed:
        The content currently on disk / in VCS.
    rendered:
        The output of render_bidsignore() for the current entries.

    Returns
    -------
    (drifted, details)
        drifted is True when committed != rendered.
        details is a human-readable diff summary (empty string when no drift).
    """
    if committed == rendered:
        return False, ""

    committed_lines = committed.splitlines()
    rendered_lines = rendered.splitlines()

    import difflib
    diff = list(
        difflib.unified_diff(
            rendered_lines,
            committed_lines,
            fromfile="rendered (fresh)",
            tofile="committed (on-disk)",
            lineterm="",
        )
    )
    details = "\n".join(diff[:40])
    if len(diff) > 40:
        details += f"\n... ({len(diff) - 40} more diff lines)"
    return True, details
