"""Pure rendering functions for exclusion data.

Public API
----------
render_md(entries)           -> str   Markdown grouped by source with DO-NOT-EDIT stamp.
render_bidsignore(entries)   -> str   One .bidsignore glob line per exclude/trim entry.
check_md_drift(committed, rendered) -> (bool, str)   Detect drift between committed and fresh render.
check_bidsignore_drift(committed, rendered) -> (bool, str)   Same for .bidsignore content.

All functions are pure (no I/O).  The CLI writes only when --output is given.
"""
from __future__ import annotations

from collections import defaultdict
from pathlib import Path

# Project-relative path for committed human-curated collection .bidsignore
# blocks. Resolved from the package's parent directories (same convention as
# core.exclusions._REPO_ROOT).
_REPO_ROOT = Path(__file__).resolve().parents[3]
_COLLECTION_DIR = _REPO_ROOT / "data" / "exclusions"

# ---------------------------------------------------------------------------
# Stamps
# ---------------------------------------------------------------------------

_MD_STAMP = "<!-- DO NOT EDIT — generated by 'neuro-run exclusions render-md' -->"
_BIDSIGNORE_STAMP = "# DO NOT EDIT — generated by 'neuro-run exclusions render-bidsignore'"

# Actions that produce a .bidsignore line.
_BIDSIGNORE_ACTIONS = {"exclude", "trim"}


# ---------------------------------------------------------------------------
# render_md
# ---------------------------------------------------------------------------

def render_md(entries: list[dict]) -> str:
    """Render a Markdown document grouped by source from the given entries list.

    Parameters
    ----------
    entries:
        List of exclusion entry dicts (as returned by load_compiled_exclusions).

    Returns
    -------
    str
        Full Markdown document.  Deterministic: sorted by source, then by
        (subject, session, task, run) within each source group.
    """
    lines: list[str] = [
        _MD_STAMP,
        "",
        "# Exclusions",
        "",
    ]

    if not entries:
        lines.append("*(no exclusions)*")
        lines.append("")
        return "\n".join(lines) + "\n"

    by_source: dict[str, list[dict]] = defaultdict(list)
    for e in entries:
        by_source[e.get("source", "unknown")].append(e)

    for source in sorted(by_source.keys()):
        lines.append(f"## Source: {source}")
        lines.append("")
        lines.append("| Subject | Session | Task | Run | Action | Reason |")
        lines.append("|---|---|---|---|---|---|")
        group = sorted(
            by_source[source],
            key=lambda e: (
                e.get("subject", ""),
                e.get("session", ""),
                e.get("task", ""),
                e.get("run", ""),
            ),
        )
        for e in group:
            lines.append(
                f"| {e.get('subject', '-')} "
                f"| {e.get('session', '-')} "
                f"| {e.get('task', '-')} "
                f"| {e.get('run', '-')} "
                f"| {e.get('action', '-')} "
                f"| {e.get('reason', '')} |"
            )
        lines.append("")

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# render_bidsignore
# ---------------------------------------------------------------------------

def _entry_to_bidsignore_glob(entry: dict) -> str | None:
    """Convert a single exclusion entry to a .bidsignore glob line.

    Returns None for entries with actions that should NOT produce a glob
    (e.g. force-include).

    Glob form (functional BOLD, matching the real .bidsignore convention):
        sub-{subject}/ses-{session}/func/sub-{subject}_ses-{session}_task-{task}_run-{run}_echo-*_bold.*

    Field values in entries already carry BIDS prefixes (sub-, ses-, run-)
    but task is stored BARE.  The function normalises to the form the real
    .bidsignore uses.
    """
    action = entry.get("action", "")
    if action not in _BIDSIGNORE_ACTIONS:
        return None

    subject = entry.get("subject", "")    # e.g. "sub-s10"
    session = entry.get("session", "")    # e.g. "ses-05"
    task = entry.get("task", "")          # BARE, e.g. "goNogo"
    run = entry.get("run", "run-*")       # e.g. "run-1" or "run-*"

    # Normalise subject/session to have BIDS prefix.
    if not subject.startswith("sub-"):
        subject = f"sub-{subject}"
    if not session.startswith("ses-"):
        session = f"ses-{session}"
    # task is stored bare; prepend task- for the glob.
    if not task.startswith("task-"):
        task_tag = f"task-{task}"
    else:
        task_tag = task
    # run already has prefix (run-1 / run-*).
    if not run.startswith("run-"):
        run = f"run-{run}"

    return (
        f"{subject}/{session}/func/"
        f"{subject}_{session}_{task_tag}_{run}_echo-*_bold.*"
    )


def render_bidsignore(entries: list[dict]) -> str:
    """Render a .bidsignore file from the given entries list.

    Only entries with action in {'exclude', 'trim'} produce glob lines.
    Lines are sorted for determinism.

    Parameters
    ----------
    entries:
        List of exclusion entry dicts.

    Returns
    -------
    str
        Full .bidsignore content (header comment + sorted glob lines).
    """
    lines: list[str] = [_BIDSIGNORE_STAMP, ""]

    globs: list[str] = []
    for e in entries:
        glob = _entry_to_bidsignore_glob(e)
        if glob is not None:
            globs.append(glob)

    globs_sorted = sorted(set(globs))
    lines.extend(globs_sorted)

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Collection block (committed, human-curated) + concatenation
# ---------------------------------------------------------------------------

def collection_path(dataset_name: str) -> Path:
    """Path to the committed human-curated collection .bidsignore for a dataset.

    e.g. data/exclusions/discovery_collection.bidsignore.  The file holds the
    data-collection / anatomical / wildcard exclusions that do NOT come from a
    QC generator and so cannot be reconstructed from the compiled entries.
    """
    return _COLLECTION_DIR / f"{dataset_name}_collection.bidsignore"


def render_bidsignore_with_collection(
    dataset_name: str, entries: list[dict],
) -> str:
    """Render the full .bidsignore = committed collection block + generated QC.

    The committed human-curated collection block (read VERBATIM from
    data/exclusions/<dataset>_collection.bidsignore) comes FIRST and carries
    its own header.  The generated QC scan-lines (from render_bidsignore over
    the compiled entries) follow, under their own DO-NOT-EDIT stamp.

    Parameters
    ----------
    dataset_name:
        Dataset whose collection block to prepend (e.g. "discovery").
    entries:
        Compiled exclusion entries (the QC-generated portion).

    Raises
    ------
    FileNotFoundError
        If the committed collection file is missing — never silently emit a
        partial .bidsignore that drops the collection exclusions.
    """
    coll_path = collection_path(dataset_name)
    if not coll_path.is_file():
        raise FileNotFoundError(
            f"Committed collection .bidsignore not found for dataset "
            f"'{dataset_name}': {coll_path}. This file holds the human-curated "
            f"data-collection/anatomical exclusions and must be committed."
        )
    collection_block = coll_path.read_text()
    # Drop source="collection" entries from the generated QC section: they are
    # already present verbatim in the prepended human-curated block above (J1
    # folds the collection layer into the compiled set, so compiled entries now
    # include them). Rendering them again would duplicate every collection glob.
    qc_entries = [e for e in entries if e.get("source") != "collection"]
    generated = render_bidsignore(qc_entries)

    # Collection block carries its own header; separate the two blocks with a
    # blank line so the boundary is visually clear.
    if not collection_block.endswith("\n"):
        collection_block += "\n"
    return collection_block + "\n" + generated


# ---------------------------------------------------------------------------
# Drift detection helpers
# ---------------------------------------------------------------------------

def check_md_drift(committed: str, rendered: str) -> tuple[bool, str]:
    """Compare a committed Markdown artifact against a freshly rendered version.

    Parameters
    ----------
    committed:
        The content currently on disk / in VCS.
    rendered:
        The output of render_md() for the current entries.

    Returns
    -------
    (drifted, details)
        drifted is True when committed != rendered.
        details is a human-readable diff summary (empty string when no drift).
    """
    if committed == rendered:
        return False, ""

    committed_lines = committed.splitlines()
    rendered_lines = rendered.splitlines()

    import difflib
    diff = list(
        difflib.unified_diff(
            rendered_lines,
            committed_lines,
            fromfile="rendered (fresh)",
            tofile="committed (on-disk)",
            lineterm="",
        )
    )
    details = "\n".join(diff[:40])  # cap for readability
    if len(diff) > 40:
        details += f"\n... ({len(diff) - 40} more diff lines)"
    return True, details


def check_bidsignore_drift(committed: str, rendered: str) -> tuple[bool, str]:
    """Compare a committed .bidsignore artifact against a freshly rendered version.

    Parameters
    ----------
    committed:
        The content currently on disk / in VCS.
    rendered:
        The output of render_bidsignore() for the current entries.

    Returns
    -------
    (drifted, details)
        drifted is True when committed != rendered.
        details is a human-readable diff summary (empty string when no drift).
    """
    if committed == rendered:
        return False, ""

    committed_lines = committed.splitlines()
    rendered_lines = rendered.splitlines()

    import difflib
    diff = list(
        difflib.unified_diff(
            rendered_lines,
            committed_lines,
            fromfile="rendered (fresh)",
            tofile="committed (on-disk)",
            lineterm="",
        )
    )
    details = "\n".join(diff[:40])
    if len(diff) > 40:
        details += f"\n... ({len(diff) - 40} more diff lines)"
    return True, details
