from __future__ import annotations

import json
import logging
import time
from pathlib import Path

logger = logging.getLogger(__name__)


ENTITY_ORDER = ("task", "acq", "dir", "run", "echo", "recording")


def bids_filename(subject: str, session: str, **entities: str | int) -> str:
    suffix = entities.pop("suffix", None)
    parts = [f"sub-{subject}", session]
    for key in ENTITY_ORDER:
        if key in entities:
            parts.append(f"{key}-{entities[key]}")
    stem = "_".join(parts)
    if suffix:
        stem = f"{stem}_{suffix}"
    return stem


def patch_sidecar(
    sidecar_path: str | Path,
    b0_field_identifier: str | None = None,
    b0_field_source: str | None = None,
    **extra_fields,
) -> None:
    """Patch a BIDS JSON sidecar with additional metadata fields.

    Args:
        sidecar_path: Path to JSON sidecar file
        b0_field_identifier: B0FieldIdentifier to add
        b0_field_source: B0FieldSource to add
        **extra_fields: Additional fields to patch

    Raises:
        json.JSONDecodeError: If JSON is invalid
        IOError: If file cannot be read/written
    """
    sidecar_path = Path(sidecar_path)

    # Read and validate JSON
    json_content = sidecar_path.read_text()
    data = json.loads(json_content)  # Will raise JSONDecodeError if invalid

    # Patch fields
    if b0_field_identifier is not None:
        data["B0FieldIdentifier"] = b0_field_identifier
    if b0_field_source is not None:
        data["B0FieldSource"] = b0_field_source
    data.update(extra_fields)

    # Write with formatting
    sidecar_path.write_text(json.dumps(data, indent=2))


def write_dataset_description(output_dir: str | Path, name: str) -> None:
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    desc = {
        "Name": name,
        "BIDSVersion": "1.10.0",
        "DatasetType": "raw",
        "Authors": ["Patrick Bissett", "Russell Poldrack", "Logan Bennett"],
        "GeneratedBy": [{"Name": "neuro-workflow bidsify", "Version": "0.2.0"}],
    }
    (output_dir / "dataset_description.json").write_text(json.dumps(desc, indent=2))


def write_readme(output_dir: str | Path, name: str) -> None:
    output_dir = Path(output_dir)
    readme = output_dir / "README"
    if not readme.exists():
        readme.write_text(
            f"{name}\n\n"
            f"Generated by neuro-workflow bidsify.\n"
            f"See sourcedata/ for provenance and reconciliation details.\n"
        )


def download_and_place(acq, file_obj, dest_path: str | Path, max_retries: int = 3) -> dict:
    dest_path = Path(dest_path)
    dest_path.parent.mkdir(parents=True, exist_ok=True)
    for attempt in range(max_retries):
        try:
            acq.download_file(file_obj.name, str(dest_path))
            break
        except Exception as exc:
            # Remove partial file before retry or re-raise
            if dest_path.exists():
                dest_path.unlink()
            if attempt < max_retries - 1:
                wait = 2 ** attempt
                logger.warning(
                    "Download failed for %s (attempt %d/%d), retrying in %ds: %s",
                    file_obj.name, attempt + 1, max_retries, wait, exc,
                )
                time.sleep(wait)
            else:
                raise
    return {
        "fw_filename": file_obj.name,
        "bids_path": str(dest_path),
        "size": file_obj.size,
        "created": file_obj.created.isoformat() if file_obj.created else None,
    }
