"""Integration of BOLD analyzer with bidsify workflow."""

import logging
from pathlib import Path
from typing import Optional

from neuro_workflow.bids_validation.bold_analyzer import BoldAnalyzer

logger = logging.getLogger(__name__)


def run_bold_analysis_and_update_bidsignore(
    bids_dir: Path,
    tr_threshold_minutes: float = 3.0,
    merge_bidsignore: bool = True,
    verbose: bool = False,
) -> None:
    """Run BOLD analysis on completed BIDS directory and optionally update .bidsignore.

    This function:
    1. Initializes BoldAnalyzer with the BIDS directory
    2. Runs analysis to detect BOLD scan issues
    3. Saves analysis results to {bids_dir}/.bids-validation/analysis.json
    4. Merges new .bidsignore entries into existing .bidsignore (if merge_bidsignore=True)

    Parameters
    ----------
    bids_dir : Path
        Path to BIDS root directory (must exist and contain sub-*/ses-*/func/)
    tr_threshold_minutes : float, optional
        Threshold for flagging short scans (default: 3.0 minutes)
    merge_bidsignore : bool, optional
        If True, merge new entries into existing .bidsignore (default: True)
    verbose : bool, optional
        Enable verbose logging (default: False)

    Raises
    ------
    FileNotFoundError
        If BIDS directory does not exist
    """
    bids_dir = Path(bids_dir)

    if not bids_dir.exists():
        raise FileNotFoundError(f"BIDS directory does not exist: {bids_dir}")

    logger.info(f"Running BOLD analysis on {bids_dir}")

    # Initialize analyzer
    analyzer = BoldAnalyzer(
        bids_dir,
        tr_threshold_minutes=tr_threshold_minutes,
        verbose=verbose,
    )

    # Run analysis and save report
    analysis_dir = bids_dir / ".bids-validation"
    analysis_file = analysis_dir / "analysis.json"

    analyzer.save_analysis_report(analysis_file)
    logger.info(f"Saved analysis report to {analysis_file}")

    # Generate .bidsignore entries
    bidsignore_entries = analyzer.generate_bidsignore_entries()

    if merge_bidsignore:
        _merge_bidsignore(bids_dir, bidsignore_entries, verbose=verbose)
    else:
        # Just log what would be added
        if bidsignore_entries.strip() and not bidsignore_entries.startswith("# No BOLD"):
            logger.info(
                f"BOLD analysis found issues. Use merge_bidsignore=True to add to .bidsignore"
            )


def _merge_bidsignore(
    bids_dir: Path, new_entries: str, verbose: bool = False
) -> None:
    """Merge new .bidsignore entries into existing .bidsignore file.

    Parameters
    ----------
    bids_dir : Path
        Path to BIDS root directory
    new_entries : str
        New .bidsignore content to merge (with comments and patterns)
    verbose : bool
        Enable verbose logging
    """
    bidsignore_path = bids_dir / ".bidsignore"

    # Parse new entries to extract patterns only (skip comments and blank lines)
    new_patterns = set()
    for line in new_entries.split("\n"):
        line = line.strip()
        if line and not line.startswith("#"):
            new_patterns.add(line)

    if not new_patterns:
        logger.info("No new BOLD issues to add to .bidsignore")
        return

    # Read existing .bidsignore
    existing_patterns = set()
    if bidsignore_path.exists():
        for line in bidsignore_path.read_text().split("\n"):
            line = line.strip()
            if line and not line.startswith("#"):
                existing_patterns.add(line)

    # Merge (keep both)
    all_patterns = existing_patterns | new_patterns
    num_new = len(all_patterns - existing_patterns)

    if num_new == 0:
        logger.info("No new patterns to add to .bidsignore")
        return

    # Rebuild .bidsignore with header and sorted patterns
    lines = [
        "# BIDS validation exclusions",
        "# Generated by bidsify with BOLD analyzer",
        "# See .bids-validation/analysis.json for details",
        "",
    ]
    for pattern in sorted(all_patterns):
        lines.append(pattern)

    bidsignore_path.write_text("\n".join(lines) + "\n")
    logger.info(
        f"Updated .bidsignore: added {num_new} new patterns "
        f"({len(all_patterns)} total patterns)"
    )
    if verbose:
        logger.debug(f"New patterns added: {', '.join(sorted(new_patterns - existing_patterns))}")
