def test_thresholds_exist():
    from neuro_workflow.events.qc_globals import (
        STOP_SUCCESS_ACC_LOW_THRESHOLD,
        STOP_SUCCESS_ACC_HIGH_THRESHOLD,
        GO_RT_THRESHOLD_FMRI,
        GONOGO_GO_ACC_THRESHOLD_1,
        GONOGO_NOGO_ACC_THRESHOLD_1,
        ACC_THRESHOLD,
        OMISSION_RATE_THRESHOLD,
        LAST_N_TEST_TRIALS,
    )
    assert STOP_SUCCESS_ACC_LOW_THRESHOLD == 0.25
    assert STOP_SUCCESS_ACC_HIGH_THRESHOLD == 0.75
    assert GO_RT_THRESHOLD_FMRI == 1000
    assert ACC_THRESHOLD == 0.55
    assert OMISSION_RATE_THRESHOLD == 0.25
    assert LAST_N_TEST_TRIALS == 10

def test_nback_thresholds():
    from neuro_workflow.events.qc_globals import (
        NBACK_1BACK_MATCH_ACC_COMBINED_THRESHOLD_1,
        NBACK_1BACK_MISMATCH_ACC_COMBINED_THRESHOLD_1,
        NBACK_2BACK_MATCH_ACC_COMBINED_THRESHOLD_1,
        NBACK_2BACK_MISMATCH_ACC_COMBINED_THRESHOLD_1,
    )
    assert NBACK_1BACK_MATCH_ACC_COMBINED_THRESHOLD_1 == 0.2
    assert NBACK_1BACK_MISMATCH_ACC_COMBINED_THRESHOLD_1 == 0.75
