#!/usr/bin/env python3
"""Copy raw behavioral CSVs to BIDS sourcedata layout using static mapping config.

Reads session mappings from config/behavioral_session_mapping.json (generated by
generate_behavioral_mapping.py) and copies matching CSVs to the BIDS sourcedata
directory structure.

Usage:
    python scripts/rename_behavioral_to_sourcedata.py \
        --input-dir /oak/.../behavioral_data/raw_cleaned \
        --output-dir /scratch/users/logben/discovery_bids/sourcedata/behavioral \
        --sample discovery \
        [--bids-dir /scratch/users/logben/discovery_bids] \
        [--dry-run]
"""
import argparse
import json
import logging
import re
import shutil
from datetime import datetime, timezone
from pathlib import Path

log = logging.getLogger(__name__)

# Canonical mapping from raw long names to BIDS camelCase task names
LONG_NAME_TO_BIDS = {
    "stop_signal": "stopSignal",
    "flanker": "flanker",
    "go_nogo": "goNogo",
    "n_back": "nBack",
    "cued_task_switching": "cuedTS",
    "spatial_task_switching": "spatialTS",
    "directed_forgetting": "directedForgetting",
    "shape_matching": "shapeMatching",
    "stop_signal_with_flanker": "stopSignalWFlanker",
    "stop_signal_with_directed_forgetting": "stopSignalWDirectedForgetting",
    "directed_forgetting_with_flanker": "directedForgettingWFlanker",
    "directed_forgetting_with_cued_task_switching": "directedForgettingWCuedTS",
    "cued_task_switching_with_directed_forgetting": "directedForgettingWCuedTS",
    "spatial_task_switching_with_cued_task_switching": "spatialTSWCuedTS",
    "flanker_with_shape_matching": "flankerWShapeMatching",
    "flanker_with_cued_task_switching": "cuedTSWFlanker",
    "n_back_with_shape_matching": "nBackWShapeMatching",
    "n_back_with_spatial_task_switching": "nBackWSpatialTS",
    "shape_matching_with_cued_task_switching": "shapeMatchingWCuedTS",
    "shape_matching_with_spatial_task_switching": "spatialTSWShapeMatching",
}

# Reverse mapping for BIDS-style filenames (camelCase and dash-separated)
_BIDS_TASK_ALIASES = {
    "go-nogo": "goNogo",
    "stop-signal": "stopSignal",
    "shape-matching": "shapeMatching",
    "spatial-task-switching": "spatialTS",
    "cued-task-switching": "cuedTS",
    "directed-forgetting": "directedForgetting",
    "n-back": "nBack",
    "nBack": "nBack",
    "stopSignal": "stopSignal",
    "goNogo": "goNogo",
    "shapeMatching": "shapeMatching",
    "spatialTaskSwitching": "spatialTS",
    "cuedTaskSwitching": "cuedTS",
    "directedForgetting": "directedForgetting",
    "flanker": "flanker",
    # Dual tasks in BIDS-style
    "stop_signal_with_flanker": "stopSignalWFlanker",
    "stop_signal_with_directed_forgetting": "stopSignalWDirectedForgetting",
    "directed_forgetting_with_flanker": "directedForgettingWFlanker",
}


def parse_csv_filename(filename: str) -> str | None:
    """Extract canonical BIDS task name from any of the three naming patterns.

    Patterns:
    1. Descriptive: stop_signal_single_task_network__fmri_results (3).csv
    2. BIDS dash-separated: sub-s29_ses-01_task-stop-signal_desc-raw.csv
    3. BIDS camelCase: sub-s76_ses-01_task-stopSignal_desc-beh.csv

    Returns the camelCase BIDS task name, or None if not recognized.
    """
    # Pattern 1: descriptive style (with or without copy number)
    # Remove copy number like " (3)" and .csv extension
    base = re.sub(r"\s*\(\d+\)", "", filename)
    base = re.sub(r"\s*copy", "", base)
    base = base.replace(".csv", "")

    if "__fmri" in base:
        long_name = base.split("__fmri")[0]
        if "_single_task_network" in long_name:
            long_name = long_name.split("_single_task_network")[0]
        return LONG_NAME_TO_BIDS.get(long_name)

    # Pattern 2/3: BIDS-style with task- entity
    m = re.search(r"task-([^_]+)", base)
    if m:
        task_raw = m.group(1)
        # Check direct alias
        if task_raw in _BIDS_TASK_ALIASES:
            return _BIDS_TASK_ALIASES[task_raw]
        # Check if it's already a valid BIDS name
        if task_raw in LONG_NAME_TO_BIDS.values():
            return task_raw
        # Try converting dashes to underscores for dual task lookup
        task_underscore = task_raw.replace("-", "_")
        if task_underscore in LONG_NAME_TO_BIDS:
            return LONG_NAME_TO_BIDS[task_underscore]

    # Pattern for BIDS-style dual tasks with underscores in task field
    # e.g., sub-s29_ses_11_task-stop_signal_with_flanker_desc_raw.csv
    m2 = re.search(r"task-(.+?)_desc", base)
    if m2:
        task_raw = m2.group(1)
        task_underscore = task_raw.replace("-", "_")
        if task_underscore in LONG_NAME_TO_BIDS:
            return LONG_NAME_TO_BIDS[task_underscore]
        if task_raw in _BIDS_TASK_ALIASES:
            return _BIDS_TASK_ALIASES[task_raw]

    return None


def zero_pad_session(session: str) -> str:
    """Zero-pad session label: ses-1 -> ses-01, ses-01 stays ses-01."""
    m = re.match(r"ses-(\d+)", session)
    if m:
        return f"ses-{int(m.group(1)):02d}"
    return session


def build_output_path(
    output_root: Path, subject: str, session: str, task_name: str
) -> Path:
    """Build BIDS sourcedata output path."""
    sub_label = subject if subject.startswith("sub-") else f"sub-{subject}"
    filename = f"{sub_label}_{session}_task-{task_name}_beh.csv"
    return output_root / sub_label / session / "beh" / filename


SKIP_DIRS = {"dropped_subjects", "exclusions", "pretouch", "practice", "extra"}


def load_config() -> dict:
    """Load behavioral_session_mapping.json from the config directory."""
    config_path = Path(__file__).resolve().parent.parent / "config" / "behavioral_session_mapping.json"
    if not config_path.exists():
        raise FileNotFoundError(f"Config not found: {config_path}")
    with open(config_path) as f:
        return json.load(f)


def main():
    parser = argparse.ArgumentParser(
        description="Copy behavioral CSVs to BIDS sourcedata layout using static mapping config"
    )
    parser.add_argument("--input-dir", required=True, type=Path, help="raw_cleaned directory")
    parser.add_argument("--output-dir", required=True, type=Path, help="sourcedata/behavioral output directory")
    parser.add_argument(
        "--sample",
        required=True,
        choices=["discovery", "validation", "all"],
        help="Which sample to process",
    )
    parser.add_argument(
        "--bids-dir",
        type=Path,
        default=None,
        help="BIDS root for writing .bidsignore (default: output-dir/../../)",
    )
    parser.add_argument("--dry-run", action="store_true", help="Print plan without copying")
    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")

    # Determine BIDS root for .bidsignore
    bids_root = args.bids_dir if args.bids_dir else args.output_dir.parent.parent

    config = load_config()
    subjects = config["subjects"]

    # Filter by sample
    if args.sample != "all":
        subjects = {
            sub: info for sub, info in subjects.items()
            if info["sample"] == args.sample
        }

    # Output session mapping (subset relevant to this run)
    session_mapping = {
        "generated": datetime.now(timezone.utc).isoformat(),
        "sample": args.sample,
        "config_generated": config.get("generated", "unknown"),
        "subjects": {},
    }

    # Collect .bidsignore entries
    bidsignore_entries = []

    total_files = 0
    total_subjects = 0
    total_skipped_subjects = 0

    for subject, info in sorted(subjects.items()):
        # Skip excluded subjects
        if info.get("excluded", False):
            log.info(
                "Skipping excluded subject %s: %s",
                subject,
                info.get("exclude_reason", "no reason given"),
            )
            bidsignore_entries.append(f"sub-{subject}/")
            total_skipped_subjects += 1
            continue

        mappings = info.get("mappings", [])
        if not mappings:
            log.warning("No mappings for %s — skipping", subject)
            continue

        subject_files = 0
        subject_mapping_out = []

        for mapping in mappings:
            raw_ses = mapping["raw"]
            bids_ses = mapping["bids"]
            allowed_tasks = set(mapping["tasks"])

            # Find raw CSVs in input_dir/{subject}/{raw_ses}/
            raw_ses_dir = args.input_dir / subject / raw_ses
            if not raw_ses_dir.exists():
                # Try zero-padded and unpadded variants
                alt_ses = zero_pad_session(raw_ses)
                alt_dir = args.input_dir / subject / alt_ses
                if alt_dir.exists():
                    raw_ses_dir = alt_dir
                else:
                    log.warning(
                        "%s: raw session dir not found: %s",
                        subject,
                        raw_ses_dir,
                    )
                    continue

            copied_tasks = []
            for csv_file in sorted(raw_ses_dir.glob("*.csv")):
                if "practice" in str(csv_file).lower():
                    continue

                task_name = parse_csv_filename(csv_file.name)
                if task_name is None:
                    log.warning("Unrecognized file: %s", csv_file)
                    continue

                if task_name not in allowed_tasks:
                    log.debug(
                        "%s/%s: task %s not in mapping tasks %s — skipping %s",
                        subject,
                        raw_ses,
                        task_name,
                        sorted(allowed_tasks),
                        csv_file.name,
                    )
                    continue

                out_path = build_output_path(args.output_dir, subject, bids_ses, task_name)
                if not args.dry_run:
                    out_path.parent.mkdir(parents=True, exist_ok=True)
                    shutil.copy2(csv_file, out_path)
                else:
                    log.info("  %s -> %s", csv_file, out_path)

                copied_tasks.append(task_name)
                subject_files += 1
                total_files += 1

            subject_mapping_out.append({
                "raw_session": raw_ses,
                "bids_session": bids_ses,
                "bids_date": mapping.get("bids_date"),
                "tasks_copied": sorted(copied_tasks),
            })

        # Record irreconcilable runs for .bidsignore
        for run in info.get("irreconcilable_bids_runs", []):
            if run["task"] == "*":
                entry = f"sub-{subject}/{run['session']}/"
            else:
                entry = f"sub-{subject}/{run['session']}/func/*task-{run['task']}*"
            bidsignore_entries.append(entry)

        if subject_files > 0:
            total_subjects += 1
            log.info("%s: copied %d files across %d sessions", subject, subject_files, len(mappings))

        session_mapping["subjects"][subject] = {
            "mappings": subject_mapping_out,
            "skipped_bids": info.get("skipped_bids", []),
            "unmatched_raw": info.get("unmatched_raw", []),
            "irreconcilable_bids_runs": info.get("irreconcilable_bids_runs", []),
        }

    # Write session_mapping.json
    if not args.dry_run:
        args.output_dir.mkdir(parents=True, exist_ok=True)
        mapping_path = args.output_dir / "session_mapping.json"
        mapping_path.write_text(json.dumps(session_mapping, indent=2) + "\n")
        log.info("Wrote session mapping to %s", mapping_path)
    else:
        log.info("Dry run — session_mapping.json not written")

    # Write .bidsignore (append, don't overwrite)
    if bidsignore_entries:
        bidsignore_path = bids_root / ".bidsignore"
        if not args.dry_run:
            bids_root.mkdir(parents=True, exist_ok=True)
            # Read existing entries to avoid duplicates
            existing = set()
            if bidsignore_path.exists():
                existing = set(bidsignore_path.read_text().splitlines())
            new_entries = [e for e in bidsignore_entries if e not in existing]
            if new_entries:
                with open(bidsignore_path, "a") as f:
                    f.write("\n".join(new_entries) + "\n")
                log.info(
                    "Appended %d entries to %s", len(new_entries), bidsignore_path
                )
        else:
            log.info("Dry run — .bidsignore entries that would be written:")
            for entry in bidsignore_entries:
                log.info("  %s", entry)

    log.info(
        "Done: %d files for %d subjects (%d excluded)",
        total_files,
        total_subjects,
        total_skipped_subjects,
    )


if __name__ == "__main__":
    main()
