"""Regenerate EXCLUSIONS.md from compiled_exclusions.json (both cohorts).

Reads the committed lockfile for each cohort, groups entries by source
(motion / behavioral / qa_decisions / etc.), produces a markdown table per
source per cohort. Manual notes in a `## Manual notes` section are preserved.
"""
from __future__ import annotations

import argparse
import json
import sys
from collections import defaultdict
from pathlib import Path


_AUTO_HEADER = '<!-- AUTO-GENERATED by scripts/render_exclusions_md.py — do not edit above this line -->'
_MANUAL_HEADER = '## Manual notes (preserved across regenerations)'


def render_md(compiled_paths: dict[str, Path]) -> str:
    lines = ['# Exclusions', '', _AUTO_HEADER, '']
    for cohort, path in compiled_paths.items():
        lines.append(f'## {cohort}')
        lines.append('')
        if not path.exists():
            lines.append(f'(lockfile not found: {path})')
            lines.append('')
            continue
        data = json.loads(path.read_text())
        entries = data.get('entries', [])
        if not entries:
            lines.append('(no exclusions)')
            lines.append('')
            continue

        by_source: dict[str, list] = defaultdict(list)
        for e in entries:
            by_source[e['source']].append(e)

        for source in sorted(by_source.keys()):
            lines.append(f'### Source: {source}')
            lines.append('')
            lines.append('| Subject | Session | Task | Run | Reason |')
            lines.append('|---|---|---|---|---|')
            for e in by_source[source]:
                lines.append(
                    f"| {e['subject']} | {e.get('session', '-')} | "
                    f"{e.get('task', '-')} | {e.get('run', '-')} | {e.get('reason', '')} |"
                )
            lines.append('')
    return '\n'.join(lines) + '\n'


def _preserve_manual_notes(existing_md: str | None) -> str:
    if existing_md is None or _MANUAL_HEADER not in existing_md:
        return _MANUAL_HEADER + '\n\n(none)\n'
    return existing_md[existing_md.index(_MANUAL_HEADER):]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--compiled', nargs='+', required=True,
                        help='cohort=path/to/compiled_exclusions.json pairs')
    parser.add_argument('--output-md', type=Path, required=True,
                        help='Path to EXCLUSIONS.md to write')
    args = parser.parse_args()

    compiled_paths: dict[str, Path] = {}
    for pair in args.compiled:
        cohort, path = pair.split('=', 1)
        compiled_paths[cohort] = Path(path).expanduser()

    auto = render_md(compiled_paths)
    existing = args.output_md.read_text() if args.output_md.exists() else None
    manual = _preserve_manual_notes(existing)
    args.output_md.write_text(auto + '\n' + manual)
    print(f'Wrote {args.output_md}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
